/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Metodo;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author onefr
 */
public class Metodo_ms extends javax.swing.JFrame {

    fondo f = new fondo();
    public Metodo_ms() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_principal = new fondo();
        jL_ms = new javax.swing.JLabel();
        jL_OB = new javax.swing.JLabel();
        jB_MAXIMIZAR = new javax.swing.JButton();
        jB_MINIMIZAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_principal.setBackground(new java.awt.Color(255, 255, 255));

        jL_ms.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        jL_ms.setText("Metodo Simplex");

        jL_OB.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        jL_OB.setText("OBJETIVO:");

        jB_MAXIMIZAR.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        jB_MAXIMIZAR.setText("Maximizar");
        jB_MAXIMIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MAXIMIZARActionPerformed(evt);
            }
        });

        jB_MINIMIZAR.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        jB_MINIMIZAR.setText("Minimizar");
        jB_MINIMIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MINIMIZARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_principalLayout = new javax.swing.GroupLayout(jP_principal);
        jP_principal.setLayout(jP_principalLayout);
        jP_principalLayout.setHorizontalGroup(
            jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_principalLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jL_ms)
                .addGap(297, 297, 297))
            .addGroup(jP_principalLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addGroup(jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_MINIMIZAR)
                    .addComponent(jL_OB, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_MAXIMIZAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_principalLayout.setVerticalGroup(
            jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_principalLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jL_ms)
                .addGap(62, 62, 62)
                .addComponent(jL_OB)
                .addGap(36, 36, 36)
                .addComponent(jB_MAXIMIZAR)
                .addGap(31, 31, 31)
                .addComponent(jB_MINIMIZAR)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_MAXIMIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MAXIMIZARActionPerformed
         Maximizar m = new Maximizar();
         m.setVisible(true);
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_MAXIMIZARActionPerformed

    private void jB_MINIMIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MINIMIZARActionPerformed
        Minimizar m = new Minimizar();
        m.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jB_MINIMIZARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Metodo_ms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Metodo_ms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Metodo_ms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Metodo_ms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metodo_ms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_MAXIMIZAR;
    private javax.swing.JButton jB_MINIMIZAR;
    private javax.swing.JLabel jL_OB;
    private javax.swing.JLabel jL_ms;
    private javax.swing.JPanel jP_principal;
    // End of variables declaration//GEN-END:variables
 class fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Elementos/Fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);

        }

    }
}
